import { escapeHtml } from "./html.js";

export function agentProfileRoutingHtml(appName: string): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>${escapeHtml(appName)} - Agent Profile Routing</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@400;500;600;700&display=swap" rel="stylesheet" />
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: "Space Grotesk", system-ui, sans-serif; background:#060a14; color:#e2e8f0; min-height:100vh; padding:32px 16px; }
    .shell { max-width:1180px; margin:0 auto; background:#0f172a; border:1px solid #22314f; border-radius:18px; box-shadow:0 14px 36px rgba(1,6,18,.55); overflow:hidden; }
    .header { display:flex; justify-content:space-between; align-items:flex-start; gap:18px; padding:24px 28px; border-bottom:1px solid #22314f; }
    h1 { font-size:24px; margin-bottom:6px; }
    .subtitle { color:#94a3b8; font-size:13px; line-height:1.55; max-width:760px; }
    .body { padding:24px 28px 28px; display:grid; gap:22px; }
    .toolbar { display:flex; gap:10px; flex-wrap:wrap; justify-content:flex-end; }
    .btn { padding:10px 14px; border-radius:10px; border:1px solid #22314f; background:#1e293b; color:#e2e8f0; text-decoration:none; font-size:13px; font-weight:700; cursor:pointer; font-family:inherit; }
    .btn.primary { background:#2563eb; border-color:#2563eb; }
    .btn.ghost { background:transparent; color:#94a3b8; }
    .btn.danger { background:rgba(248,113,113,.1); color:#fca5a5; }
    .card { background:#0a1325; border:1px solid #22314f; border-radius:14px; padding:18px; }
    .section-title { font-size:12px; text-transform:uppercase; letter-spacing:.08em; color:#94a3b8; margin-bottom:12px; }
    .form-grid { display:grid; grid-template-columns:repeat(3, minmax(0, 1fr)); gap:12px; align-items:end; }
    label { display:block; color:#94a3b8; font-size:12px; margin-bottom:6px; }
    select, input { width:100%; background:#08101f; color:#e2e8f0; border:1px solid #22314f; border-radius:10px; padding:10px; font-family:inherit; font-size:13px; }
    select:disabled { opacity:.45; }
    .hint { color:#64748b; font-size:12px; line-height:1.5; margin-top:10px; }
    .status { min-height:20px; color:#94a3b8; font-size:13px; }
    .error { color:#fca5a5; }
    .ok { color:#86efac; }
    table { width:100%; border-collapse:collapse; overflow:hidden; border:1px solid #22314f; border-radius:12px; }
    th, td { padding:12px; border-bottom:1px solid #22314f; text-align:left; vertical-align:top; font-size:13px; }
    th { color:#94a3b8; background:#0d1628; font-size:11px; text-transform:uppercase; letter-spacing:.08em; }
    tr:last-child td { border-bottom:0; }
    code { color:#dbeafe; font-family:ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace; font-size:12px; }
    .badge { display:inline-block; border-radius:999px; padding:4px 8px; background:#10203a; color:#93c5fd; font-size:11px; font-weight:800; margin-right:5px; margin-bottom:5px; }
    .badge.warn { background:rgba(251,191,36,.14); color:#fde68a; }
    .empty { color:#94a3b8; text-align:center; border:1px dashed #22314f; border-radius:12px; padding:24px; }
    .muted { color:#94a3b8; }
    @media (max-width: 880px) { .header { display:block; } .toolbar { justify-content:flex-start; margin-top:16px; } .form-grid { grid-template-columns:1fr; } }
  </style>
</head>
<body>
  <div class="shell">
    <div class="header">
      <div>
        <h1>Agent Profile Routing</h1>
        <div class="subtitle">Assign profiles to whole workflows, workflow actions, semantic intents, or direct-LLM actions using validated select boxes. Internal target keys are generated by the server.</div>
      </div>
      <div class="toolbar">
        <a class="btn ghost" href="/agent-profiles">Profiles</a>
        <a class="btn ghost" href="/">Back</a>
      </div>
    </div>
    <div class="body">
      <div class="card">
        <div class="section-title">Add / replace routing policy</div>
        <div class="form-grid">
          <div>
            <label for="target-type">Target type</label>
            <select id="target-type">
              <option value="preset">Preset</option>
              <option value="pipeline">Whole workflow</option>
              <option value="pipeline_action">Specific action in workflow</option>
              <option value="intent">Semantic run intent</option>
              <option value="intent_action">Specific action in semantic intent</option>
              <option value="global_action">All actions of type</option>
            </select>
          </div>
          <div data-field="preset">
            <label for="preset">Preset</label>
            <select id="preset"></select>
          </div>
          <div data-field="pipeline">
            <label for="pipeline">Workflow</label>
            <select id="pipeline"></select>
          </div>
          <div data-field="intent">
            <label for="intent">Intent</label>
            <select id="intent"></select>
          </div>
          <div data-field="action">
            <label for="action">Action</label>
            <select id="action"></select>
          </div>
          <div>
            <label for="mode">Mode</label>
            <select id="mode"></select>
          </div>
          <div>
            <label for="profile-1">Profile 1</label>
            <select id="profile-1"></select>
          </div>
          <div>
            <label for="profile-2">Profile 2 (fallback)</label>
            <select id="profile-2"><option value="">None</option></select>
          </div>
          <div>
            <label for="profile-3">Profile 3 (fallback)</label>
            <select id="profile-3"><option value="">None</option></select>
          </div>
        </div>
        <div class="hint" id="target-preview"></div>
        <div class="toolbar" style="justify-content:flex-start; margin-top:14px;">
          <button class="btn primary" id="save-policy">Save policy</button>
        </div>
      </div>

      <div class="status" id="status">Loading...</div>

      <div class="card">
        <div class="section-title">Policies</div>
        <div id="policies"></div>
      </div>
    </div>
  </div>
<script>
const state = { catalog: null, profiles: [], policies: [] };
const el = {
  status: document.getElementById('status'), policies: document.getElementById('policies'),
  type: document.getElementById('target-type'), preset: document.getElementById('preset'), pipeline: document.getElementById('pipeline'),
  intent: document.getElementById('intent'), action: document.getElementById('action'), mode: document.getElementById('mode'),
  profile1: document.getElementById('profile-1'), profile2: document.getElementById('profile-2'), profile3: document.getElementById('profile-3'),
  preview: document.getElementById('target-preview'), save: document.getElementById('save-policy')
};
function esc(value) { return String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); }
async function fetchJson(url, options) {
  const response = await fetch(url, Object.assign({ credentials:'same-origin', headers:{ 'content-type':'application/json' } }, options || {}));
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || 'Request failed');
  return data;
}
function option(value, label, disabled) { return '<option value="' + esc(value) + '"' + (disabled ? ' disabled' : '') + '>' + esc(label) + '</option>'; }
function fillSelect(select, rows, emptyLabel) {
  select.innerHTML = (emptyLabel ? option('', emptyLabel) : '') + rows.map(row => option(row.id, row.label || row.name || row.id, row.disabled)).join('');
}
function actionRows() {
  const actions = (state.catalog?.actions || []).filter(a => a.routable);
  return actions.map(a => ({ id:a.id, label:a.group + ' / ' + a.label }));
}
function pipelineActionRows() {
  const pipeline = (state.catalog?.pipelines || []).find(p => p.id === el.pipeline.value);
  const nodes = pipeline ? pipeline.nodes.filter(n => n.routable) : [];
  const byAction = new Map();
  nodes.forEach(n => { if (!byAction.has(n.action)) byAction.set(n.action, n.label + ' (' + n.action + ')'); });
  if (byAction.size === 0) return actionRows();
  return Array.from(byAction.entries()).map(([id, label]) => ({ id, label }));
}
function refreshVisibility() {
  const type = el.type.value;
  document.querySelectorAll('[data-field]').forEach(node => { node.style.display = 'none'; });
  if (type === 'preset') document.querySelector('[data-field="preset"]').style.display = '';
  if (type === 'pipeline' || type === 'pipeline_action') document.querySelector('[data-field="pipeline"]').style.display = '';
  if (type === 'intent' || type === 'intent_action') document.querySelector('[data-field="intent"]').style.display = '';
  if (type === 'pipeline_action' || type === 'intent_action' || type === 'global_action') document.querySelector('[data-field="action"]').style.display = '';
  if (type === 'pipeline_action') fillSelect(el.action, pipelineActionRows());
  else fillSelect(el.action, actionRows());
  const target = buildTarget();
  el.preview.textContent = target ? 'Target preview: ' + JSON.stringify(target) : '';
}
function buildTarget() {
  const type = el.type.value;
  if (type === 'preset') {
    const preset = (state.catalog?.presets || []).find(p => p.id === el.preset.value);
    return preset?.target || null;
  }
  if (type === 'pipeline') return el.pipeline.value ? { scope:'pipeline', pipelineId:el.pipeline.value } : null;
  if (type === 'pipeline_action') return el.pipeline.value && el.action.value ? { scope:'pipeline_action', pipelineId:el.pipeline.value, action:el.action.value } : null;
  if (type === 'intent') return el.intent.value ? { scope:'intent', intentKind:el.intent.value } : null;
  if (type === 'intent_action') return el.intent.value && el.action.value ? { scope:'intent_action', intentKind:el.intent.value, action:el.action.value } : null;
  if (type === 'global_action') return el.action.value ? { scope:'global_action', action:el.action.value } : null;
  return null;
}
function selectedMembers() {
  const ids = [el.profile1.value, el.profile2.value, el.profile3.value].filter(Boolean);
  return Array.from(new Set(ids)).map((profileId, index) => ({ profileId, ordinal:index, enabled:true }));
}
function modeRows() {
  return (state.catalog?.policyModes || []).filter(m => m.implemented).map(m => ({ id:m.id, label:m.label }));
}
function renderPolicies() {
  if (!state.policies.length) {
    el.policies.innerHTML = '<div class="empty">No routing policies yet.</div>';
    return;
  }
  const profilesById = new Map(state.profiles.map(p => [p.id, p]));
  el.policies.innerHTML = '<table><thead><tr><th>Target</th><th>Mode</th><th>Profiles</th><th></th></tr></thead><tbody>' +
    state.policies.map(policy => {
      const profiles = (policy.members || []).filter(m => m.enabled).sort((a,b) => a.ordinal - b.ordinal)
        .map(m => profilesById.get(m.profileId)?.name || m.profileId);
      return '<tr>' +
        '<td><code>' + esc(policy.targetKey) + '</code><div class="muted" style="margin-top:6px;">scope: ' + esc(policy.scope) + '</div></td>' +
        '<td><span class="badge">' + esc(policy.mode) + '</span>' + (policy.enabled ? '' : '<span class="badge warn">disabled</span>') + '</td>' +
        '<td>' + profiles.map(name => '<span class="badge">' + esc(name) + '</span>').join('') + '</td>' +
        '<td><button class="btn danger" data-delete="' + esc(policy.id) + '">Delete</button></td>' +
        '</tr>';
    }).join('') + '</tbody></table>';
  el.policies.querySelectorAll('[data-delete]').forEach(btn => btn.addEventListener('click', async () => {
    const id = btn.getAttribute('data-delete');
    if (!id || !confirm('Delete this routing policy?')) return;
    await fetchJson('/api/agent-profile-policies/' + encodeURIComponent(id), { method:'DELETE' });
    await load();
  }));
}
function renderControls() {
  const catalog = state.catalog || {};
  fillSelect(el.preset, catalog.presets || []);
  fillSelect(el.pipeline, catalog.pipelines || []);
  fillSelect(el.intent, catalog.intents || []);
  fillSelect(el.mode, modeRows());
  fillSelect(el.profile1, state.profiles, 'Choose profile');
  fillSelect(el.profile2, state.profiles, 'None');
  fillSelect(el.profile3, state.profiles, 'None');
  refreshVisibility();
}
async function savePolicy() {
  const target = buildTarget();
  const members = selectedMembers();
  if (!target) throw new Error('Select a target');
  if (!members.length) throw new Error('Select at least one profile');
  const mode = members.length > 1 ? 'fallback_chain' : el.mode.value;
  const body = { target, mode, enabled:true, members };
  await fetchJson('/api/agent-profile-policies', { method:'POST', body:JSON.stringify(body) });
}
async function load() {
  el.status.textContent = 'Loading...';
  const [catalog, profilesData, policiesData] = await Promise.all([
    fetchJson('/api/agent-profile-target-catalog'),
    fetchJson('/api/agent-profiles'),
    fetchJson('/api/agent-profile-policies')
  ]);
  state.catalog = catalog.catalog || catalog;
  state.profiles = Array.isArray(profilesData.profiles) ? profilesData.profiles : [];
  state.policies = Array.isArray(policiesData.policies) ? policiesData.policies : [];
  renderControls();
  renderPolicies();
  el.status.textContent = '';
}
[el.type, el.pipeline, el.intent, el.action, el.preset].forEach(node => node.addEventListener('change', refreshVisibility));
el.save.addEventListener('click', async () => {
  el.status.textContent = 'Saving...';
  try { await savePolicy(); el.status.innerHTML = '<span class="ok">Saved.</span>'; await load(); }
  catch (error) { el.status.innerHTML = '<span class="error">' + esc(error.message) + '</span>'; }
});
load().catch(error => { el.status.innerHTML = '<span class="error">' + esc(error.message) + '</span>'; });
</script>
</body>
</html>`;
}
