#!/usr/bin/env bash
set -euo pipefail

REPO_DIR="${1:?repo dir is required}"
PROMPT_FILE="${2:?prompt file is required}"
RUN_ID="${3:?run id is required}"

mkdir -p "$REPO_DIR"

cp "$PROMPT_FILE" "$REPO_DIR/.gooseherd-task-${RUN_ID}.md"
{
  echo ""
  echo "---"
  echo "Generated by dummy agent at $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
} >> "$REPO_DIR/.gooseherd-task-${RUN_ID}.md"

cat <<MSG >> "$REPO_DIR/README.md"

## Gooseherd Run ${RUN_ID}
This repository was updated by Gooseherd dummy agent during testing.
MSG
