name: Deploy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    uses: NetsoftHoldings/github-actions/.github/workflows/deploy-eks.yml@main
    with:
      APP_ENV: internal
      APP_NAME: ${{ vars.SERVICE_NAME }}
      APP_NAMESPACE: ${{ vars.SERVICE_NAME }}
      RELEASE_NAME: ${{ vars.SERVICE_NAME }}
      CONTAINER_REGISTRY_NAME: ${{ vars.CONTAINER_REGISTRY_NAME }}
      CONTAINER_REGISTRY_URL: ${{ vars.CONTAINER_REGISTRY_URL }}
      HELM_NEW: true
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
