name: Close stale pull requests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  stale:
    uses: NetsoftHoldings/github-actions/.github/workflows/general-stale-prs.yml@main
    secrets: inherit
